[workspace]

members = ["prototypes/paddles-macroquad", "prototypes/paddles-engine", "prototypes/breakout"]

# members = ["prototypes/*"]
# exclude = ["prototypes/.DS_Store", "prototypes/README.md"]

