[package]
name = "asterism"
description = "operationalizing operational logics one constellation at a time"
version = "0.1.0"
authors = ["Cynthia Li", "Julie Ye", "Joe Osborn"]
edition = "2018"

[dependencies]
ultraviolet = "0.4.6"
winit = "0.22.0"
winit_input_helper = "0.7.0"
macroquad = { git = "https://github.com/not-fl3/macroquad", rev = "31cff5d89ed17a6c83f39cf6568348dab25145dc" }
glam = "0.8"

# bevy takes a long time to build and we're not actively using it currently, so making this a feature
bevy_input = { version = "0.4.0", optional = true }

[features]
default = []
asterism-bevy = ["bevy_input"]
